name: trading_bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - python-dotenv
  - schedule
  - matplotlib
  - seaborn
  - gymnasium
  - stable-baselines3
  - pytorch
  - scikit-learn
  - ccxt-py
  - ipykernel
  - ta-lib
  - pip:
    - pandas-ta-classic