name: crypto_bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pandera-pandas
  - python-dotenv
  - schedule
  - matplotlib
  - gymnasium
  - stable-baselines3
  - pytorch
  - ccxt-py
  - pip:
    - pandas-ta-classic